### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Yifan-Wong** [inaamashraf/physics_informed_gnns_for_wds#1]
Hi Ashraf,

Your work is impressive! I'm following your instructions and want to evaluate the flow and head prediction on the default network (l-town). I firstly generate the .xlsx and .csv file under l-town folder by using your code 'dataset_generator.py'. Then I used 'run.py' and specified the mode to 'evaluate' and 'model_path' to 'trained_models/l_town'. It ran into an error. The traceback is as follows:

```
Traceback (most recent call last):
  File "C:\Research\physics_informed_gnns_for_wds-main\run.py", line 222, in <module>
    run(args)
  File "C:\Research\physics_informed_gnns_for_wds-main\run.py", line 151, in run
    wdn_graph, reservoirs = create_graph(args.inp_file, args.path_to_data)
  File "C:\Research\physics_informed_gnns_for_wds-main\utils\utils.py", line 233, in create_graph
    X_df_heads = scenario.get_heads()
  File "C:\Research\physics_informed_gnns_for_wds-main\utils\utils.py", line 114, in get_heads
    self.__load_heads()
  File "C:\Research\physics_informed_gnns_for_wds-main\utils\utils.py", line 103, in __load_heads
    recs: list[list] = get_sheet_data(path_to_heads, sheet=4)
python_calamine.CalamineError: Xlsx error: I/O error: The system cannot find the file specified. (os error 2)
```
![Screenshot 2024-08-05 170341](https://github.com/user-attachments/assets/4245d73f-ce24-4322-b74f-07164f505c02)

I would sincerely appreciate it if you could help me with it! Thank you!

**Comment by MengjieZhao** [comment]
Have you generated the dataset already?

**Comment by Yifan-Wong** [comment]
> Have you generated the dataset already?

Yes, I thought it was an issue with my file address.

**Comment by MengjieZhao** [comment]
> > Have you generated the dataset already?
> 
> Yes, I thought it was an issue with my file address.

I can run the code as it is on Linux, maybe you should check if you have the specific version of python_calamine and maybe also print args.path_to_data to check if the relative path is correct

**Comment by Yifan-Wong** [comment]
> > > Have you generated the dataset already?
> > 
> > 
> > Yes, I thought it was an issue with my file address.
> 
> I can run the code as it is on Linux, maybe you should check if you have the specific version of python_calamine and maybe also print args.path_to_data to check if the relative path is correct

Thanks
